# Site Settings
baseurl: ""

# Blog Setting
blog: False

# Page Settings
theme_settings:
  title: Christoph Jabs
  favicon: assets/favicon.ico

  # Profile Settings
  profile:
    image: https://s.gravatar.com/avatar/6441cc4485943f3202aa6ff355577806?s=700
    username: Christoph Jabs
    description: Master's student in computer science at the [University of Helsinki](https://www.helsinki.fi/en). Researching exact bi-objective optimization in the [Constraint Reasoning and Optimization](https://www2.helsinki.fi/en/researchgroups/constraint-reasoning-and-optimization) research group. Originally from Germany.
    webpage: https://chrjabs.github.io
    experience:
      - start: 05/2021
        end: current
        experience: CoReO group, University of Helsinki
      - start: 08/2020
        end: 06/2022
        experience: Master of Science in Computer Science, University of Helsinki
      - start: 06/2019
        end: 06/2020
        experience: Various student jobs at Robert Bosch GmbH Reutlingen
      - start: 03/2016
        end: 02/2020
        experience: Bachelor of Engineering in Mechatronics, Reutlingen University
    interests:
      - Boolean satisfiability and optimization
      - Bi-objective optimization
      - Declarative problem solving
      - Explainable artificial intelligence
    skills: 
      - skill: C++
        value: 80
      - skill: Python (pandas, numpy, ...)
        value: 85
        
  # Icons
  icons:
    email: christoph.jabs@helsinki.fi
    orcid: 0000-0003-3532-696X
    scholar: 
    publons: 
    research_gate: 
    linkedin:  # Full URL 
    github: chrjabs
    gitlab: 
    bitbucket: chrjabs
    google_plus:
    twitter: chrjabs
    youtube:
    facebook:
    instagram:

  experience_title: EXPERIENCE
  interests_title: RESEARCH INTERESTS
  skills_title: SKILLS
  projects_title: PROJECTS
  recentpubs_title: RECENT PUBLICATIONS

# Pagination
paginate: 5
paginate_path: "blog/page:num"

# Build Settings
sass:
  sass_dir: _sass
  style: :compressed
plugins: ['jekyll-paginate', 'jekyll/scholar']
bootstrap:
  assets: true

# Bibliography settings
scholar:
  bibliography: publications.bib
  bibliography_template: pubstemplate
  style: apa
  locale: en
  last_name: Jabs
  first_name: [Christoph, C.]
  sort_by: year,month
  order: descending,ascending

filtered_bibtex_keywords: [abbr, abstract, arxiv, bibtex_show, html, pdf, selected, supp, blog, code, poster, slides, website] # Filter out certain bibtex entry keywords used internally from the bib output

academicons:
  version: "1.9.1"
  integrity: "sha256-i1+4qU2G2860dGGIOJscdC30s9beBXjFfzjWLjBRsBg="
fontawesome:
  version: "5.15.4"
  integrity: "sha256-mUZM63G8m73Mcidfrv5E+Y61y7a12O5mW4ezU3bxqW4="
jquery:
  version: "3.6.0"
  integrity: "sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4="